Add teamcity support v2 + refactoring
ozonru/dtrack-audit pull request #11
Opened 2021-01-28 09:02 UTC by agentram

Hi,

I made some updates for TeamCity output and tried to refactor config generation. Sorry if this is too much of a change - when I started, one thing pulled another and so on...

This is how TC build looks now:
![Screenshot 2021-01-28 at 11 49 00](https://user-images.githubusercontent.com/37303331/106113077-19f1da80-615f-11eb-9232-2553098f7a4d.png)
It contains information about all tested libraries (total number of tests) and failed tests for libraries with vulnerabilities. You can also see a description of the vulnerability in the test output.

2021-01-29 20:10 UTC, agentram commented on cmd/dtrack-audit/main.go
> +	"github.com/agentram/dtrack-audit/internal/dtrack"
Please note that I changed the import path to have the ability to run go get from my branch:
```
go get github.com/agentram/dtrack-audit/cmd/dtrack-audit@add_teamcity_support_v2
```
We can put it back when it's ready to merge.

2021-01-29 20:10 UTC, agentram commented on cmd/dtrack-audit/teamcity.go
> +	"github.com/agentram/dtrack-audit/internal/dtrack"
Please note that I changed the import path to have the ability to run go get from my branch:
```
go get github.com/agentram/dtrack-audit/cmd/dtrack-audit@add_teamcity_support_v2
```
We can put it back when it's ready to merge.

2021-02-10 14:47 UTC, oxdef commented
Hi!

Thanks for the MR and sorry for delay. If you don't mind I suggest to split into small ones: config and TeamCity support v2.

2021-02-10 17:15 UTC, agentram commented
No problems, I will prepare a MR for config soon.

2021-02-10 17:46 UTC, agentram commented
I will merge https://github.com/ozonru/dtrack-audit/pull/11 when it's approved

2021-03-03 09:09 UTC, oxdef commented
@agentram  Sorry for the delay. I've just merged config PR and made some changes in release branch. Could you please move teamcity support code  into `/internal/dtrack/` package like for https://github.com/ozonru/dtrack-audit/blob/release/v1.0.0/internal/dtrack/config.go?

2021-03-18 21:32 UTC, agentram commented
Hi @oxdef 
I have updated the PR. Let me test it in my builds for a few days.

2021-03-19 11:19 UTC, agentram commented
@oxdef Everything is alright. You can review it.

2021-03-25 13:12 UTC, oxdef requested changes

2021-04-07 17:16 UTC, agentram commented on cmd/dtrack-audit/main.go
> -	uploadResult, err := apiClient.Upload(config.InputFileName, config.ProjectId)
Roger! I moved it back.

2021-04-07 17:16 UTC, agentram commented on cmd/dtrack-audit/main.go
> +			dtrack.PrintForTeamCity(apiClient, config)
This is done!

2021-04-15 13:30 UTC, oxdef approved these changes
@agentram 
Thanks for improved version of TeamCity support!

2021-04-15 13:30 UTC, oxdef commented on cmd/dtrack-audit/main.go
> +		findings, err := findVulnerabilities(apiClient, config)
You broken here Async mode. I will fix it in release branch.

2021-04-15 13:30 UTC, merged